#!/bin/sh
#
# Load kernel modules
#

case "$1" in
  start)
	echo "Configuring cpufreq governor..."
	echo performance >  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo performance >  /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
