#!/bin/sh
#
# Load kernel modules
#

case "$1" in
  start)
	echo "Configuring cpufreq governor..."
	echo powersave > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
	echo powersave > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
